#!/usr/bin/env bash
# Homelab storage one-click installer: Filebrowser + OnlyOffice, Immich,
# monitoring stack and Cloudflare Tunnel.
#
# Usage:
#   sudo ./install.sh                       # interactive, installs everything
#   sudo ./install.sh --stacks=storage      # only filebrowser + onlyoffice
#   sudo ./install.sh --stacks=storage,photos
#
# Stacks: storage | photos | monitoring | tunnel | all
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$REPO_DIR/.env"

STACKS="all"
for arg in "$@"; do
  case "$arg" in
    --stacks=*) STACKS="${arg#*=}" ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "Unknown option: $arg (try --help)"; exit 1 ;;
  esac
done

want() { [[ "$STACKS" == "all" ]] || [[ ",$STACKS," == *",$1,"* ]]; }

need_root() {
  if [[ "$(id -u)" -ne 0 ]]; then echo "Run as root: sudo ./install.sh"; exit 1; fi
}

prompt() { # prompt <var> <text> <default>
  local var="$1" text="$2" def="$3" val=""
  if [[ -n "${!var:-}" ]]; then return 0; fi
  if [[ -t 0 ]]; then
    read -rp "$text [$def]: " val
    printf -v "$var" "%s" "${val:-$def}"
  else
    printf -v "$var" "%s" "$def"
  fi
}

prompt_secret() { # prompt_secret <var> <text> (silent, min 5 chars)
  local var="$1" text="$2" val=""
  if [[ -n "${!var:-}" ]]; then return 0; fi
  while true; do
    read -rsp "$text: " val; echo
    if [[ "${#val}" -ge 5 ]]; then printf -v "$var" "%s" "$val"; return 0; fi
    echo "Minimum 5 characters, try again."
  done
}

rand_b64() { openssl rand -base64 "$1" | tr -d '\n'; }
rand_hex() { openssl rand -hex "$1" | tr -d '\n'; }

install_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    echo "[ok] docker + compose plugin present ($(docker --version))"
    return 0
  fi
  echo "[..] installing docker (official convenience script)..."
  curl -fsSL https://get.docker.com | sh
  echo "[ok] docker installed"
}

render_template() { # render_template <template> <dest>
  python3 - "$1" "$2" <<'EOF'
import sys
t, d = sys.argv[1], sys.argv[2]
s = open(t).read()
import os
for k in ("DRIVE_DOMAIN","OFFICE_DOMAIN","FB_ADMIN_USER","FB_ADMIN_PASS",
          "FB_AUTH_KEY","ONLYOFFICE_JWT","SITE_NAME"):
    s = s.replace("__%s__" % k, os.environ.get(k, ""))
open(d, "w").write(s)
EOF
}

main() {
  need_root
  install_docker

  echo "=== Homelab storage installer ==="
  prompt SITE_NAME      "Site name"                        "Homelab Drive"
  prompt STORAGE_PATH   "Storage folder on this host"      "/srv/storage"
  prompt FB_PORT        "Filebrowser port"                 "8080"
  prompt FB_ADMIN_USER  "Filebrowser admin username"       "admin"
  prompt_secret FB_ADMIN_PASS "Filebrowser admin password (min 5 chars)"
  prompt DRIVE_DOMAIN   "Public domain for files"          "drive.example.com"
  prompt OFFICE_DOMAIN  "Public domain for office editor"  "office.example.com"
  prompt OFFICE_BIND    "OnlyOffice LAN bind (ip:port)"    "127.0.0.1:8081"
  prompt IMMICH_PORT    "Immich port"                      "2283"
  prompt GRAFANA_PORT   "Grafana port"                     "3000"
  prompt GRAFANA_ADMIN_USER "Grafana admin username"       "admin"
  if want tunnel; then
    prompt CLOUDFLARE_TOKEN "Cloudflare tunnel token (paste, empty = skip tunnel)" ""
  else
    CLOUDFLARE_TOKEN="${CLOUDFLARE_TOKEN:-}"
  fi

  [[ -z "${ONLYOFFICE_JWT_SECRET:-}" ]] && ONLYOFFICE_JWT_SECRET="$(rand_b64 32)"
  [[ -z "${DB_PASSWORD:-}" ]]           && DB_PASSWORD="$(rand_b64 24)"
  [[ -z "${GRAFANA_ADMIN_PASSWORD:-}" ]] && GRAFANA_ADMIN_PASSWORD="$(rand_b64 16)"
  [[ -z "${FB_AUTH_KEY:-}" ]]            && FB_AUTH_KEY="$(rand_hex 32)"
  export DRIVE_DOMAIN OFFICE_DOMAIN FB_ADMIN_USER FB_ADMIN_PASS \
         FB_AUTH_KEY ONLYOFFICE_JWT_SECRET SITE_NAME
  export ONLYOFFICE_JWT="$ONLYOFFICE_JWT_SECRET"
  DB_USERNAME="${DB_USERNAME:-immich}"; DB_DATABASE_NAME="${DB_DATABASE_NAME:-immich}"
  TZ_VAL="${TZ:-Asia/Jakarta}"; IMMICH_VERSION="${IMMICH_VERSION:-release}"
  PROM_PORT="${PROM_PORT:-9090}"

  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%FT%TZ). DO NOT COMMIT.
TZ=$TZ_VAL
SITE_NAME=$SITE_NAME
STORAGE_PATH=$STORAGE_PATH
FB_PORT=$FB_PORT
FB_ADMIN_USER=$FB_ADMIN_USER
FB_ADMIN_PASS=$FB_ADMIN_PASS
DRIVE_DOMAIN=$DRIVE_DOMAIN
OFFICE_DOMAIN=$OFFICE_DOMAIN
OFFICE_BIND=$OFFICE_BIND
ONLYOFFICE_JWT_SECRET=$ONLYOFFICE_JWT_SECRET
FB_AUTH_KEY=$FB_AUTH_KEY
IMMICH_PORT=$IMMICH_PORT
IMMICH_VERSION=$IMMICH_VERSION
DB_USERNAME=$DB_USERNAME
DB_DATABASE_NAME=$DB_DATABASE_NAME
DB_PASSWORD=$DB_PASSWORD
PROM_PORT=$PROM_PORT
GRAFANA_PORT=$GRAFANA_PORT
GRAFANA_ADMIN_USER=$GRAFANA_ADMIN_USER
GRAFANA_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
CLOUDFLARE_TOKEN=$CLOUDFLARE_TOKEN
EOF
  chmod 600 "$ENV_FILE"
  echo "[ok] wrote .env (mode 600, git-ignored)"

  # ---------- storage: filebrowser + onlyoffice ----------
  if want storage; then
    echo "--- stack: storage ---"
    mkdir -p "$REPO_DIR/filebrowser/data" "$STORAGE_PATH"
    cp -f "$ENV_FILE" "$REPO_DIR/filebrowser/.env"
    if [[ ! -f "$REPO_DIR/filebrowser/data/config.yaml" ]]; then
      render_template "$REPO_DIR/filebrowser/config.template.yaml" \
                      "$REPO_DIR/filebrowser/data/config.yaml"
      echo "[ok] rendered filebrowser config.yaml"
    else
      echo "[..] filebrowser config.yaml exists, kept (delete to re-render)"
    fi
    chown -R 1000:1000 "$REPO_DIR/filebrowser/data"
    (cd "$REPO_DIR/filebrowser" && docker compose pull && docker compose up -d)
  fi

  # ---------- photos: immich ----------
  if want photos; then
    echo "--- stack: photos ---"
    {
      echo "UPLOAD_LOCATION=$STORAGE_PATH/immich/data"
      echo "DB_DATA_LOCATION=./postgres"
      echo "DB_USERNAME=$DB_USERNAME"
      echo "DB_DATABASE_NAME=$DB_DATABASE_NAME"
      echo "DB_PASSWORD=$DB_PASSWORD"
      echo "IMMICH_VERSION=$IMMICH_VERSION"
    } > "$REPO_DIR/immich/.env"
    chmod 600 "$REPO_DIR/immich/.env"
    sed -i 's/^- "2283:2283"$/- "${IMMICH_PORT:-2283}:2283"/' "$REPO_DIR/immich/docker-compose.yml" 2>/dev/null || true
    # ensure immich port mapping honours IMMICH_PORT even with upstream file
    if ! grep -q "IMMICH_PORT" "$REPO_DIR/immich/docker-compose.yml"; then
      echo "[..] set immich port via override"
      cat > "$REPO_DIR/immich/docker-compose.override.yml" <<'YML'
services:
  immich-server:
    ports:
      - "${IMMICH_PORT:-2283}:2283"
YML
    fi
    mkdir -p "$STORAGE_PATH/immich/data"
    (cd "$REPO_DIR/immich" && docker compose pull && docker compose up -d)
  fi

  # ---------- monitoring ----------
  if want monitoring; then
    echo "--- stack: monitoring ---"
    cp -f "$ENV_FILE" "$REPO_DIR/monitoring/.env"
    [[ -f "$REPO_DIR/monitoring/prometheus/prometheus.yml" ]] || \
      cp "$REPO_DIR/monitoring/prometheus/prometheus.example.yml" \
         "$REPO_DIR/monitoring/prometheus/prometheus.yml"
    if [[ ! -f "$REPO_DIR/monitoring/mktxp/mktxp.conf" ]]; then
      cp "$REPO_DIR/monitoring/mktxp/mktxp.example.conf" \
         "$REPO_DIR/monitoring/mktxp/mktxp.conf"
      echo "[!!] edit monitoring/mktxp/mktxp.conf with your MikroTik login (or leave disabled)"
    fi
    (cd "$REPO_DIR/monitoring" && docker compose pull && docker compose up -d)
  fi

  # ---------- tunnel ----------
  if want tunnel && [[ -n "${CLOUDFLARE_TOKEN:-}" ]]; then
    echo "--- stack: tunnel ---"
    cp -f "$ENV_FILE" "$REPO_DIR/tunnel/.env"
    (cd "$REPO_DIR/tunnel" && docker compose pull && docker compose up -d)
  elif want tunnel; then
    echo "[..] tunnel skipped (empty CLOUDFLARE_TOKEN)"
  fi

  # ---------- health check ----------
  echo "--- health check ---"
  sleep 15
  check() { # check <url> <name>
    local code
    code=$(curl -sk -m 10 -o /dev/null -w "%{http_code}" "$1" || echo 000)
    echo "[$code] $2 ($1)"
  }
  want storage && check "http://127.0.0.1:$FB_PORT/" "filebrowser"
  want storage && check "http://127.0.0.1:${OFFICE_BIND##*:}/healthcheck" "onlyoffice"
  want photos && check "http://127.0.0.1:$IMMICH_PORT/api/server/version" "immich"
  want monitoring && check "http://127.0.0.1:$GRAFANA_PORT/api/health" "grafana"

  cat <<EOF

=== Done ===
Files : http://<this-host>:$FB_PORT  (public: https://$DRIVE_DOMAIN)
Office: https://$OFFICE_DOMAIN  (welcome page is normal - open docs via Files)
EOF
  want photos && echo "Photos: http://<this-host>:$IMMICH_PORT"
  want monitoring && echo "Grafana: http://<this-host>:$GRAFANA_PORT  user=$GRAFANA_ADMIN_USER"
  cat <<EOF

Next steps:
  1. Cloudflare Zero Trust -> tunnel -> Public Hostnames (see tunnel/README.md)
  2. Open a .docx from Files to verify the OnlyOffice integration
  3. Change the Filebrowser admin password (Settings -> Users)
  4. Set up a backup cron (see scripts/backup-template.sh)
  5. Keep .env private - it is git-ignored for a reason
EOF
}

main "$@"
